# O Quarkus detectará a extensão do Postgres e criará o container automaticamente
quarkus.hibernate-orm.database.generation=drop-and-create

# Opcional: Mostrar o SQL no terminal para você acompanhar a criação das tabelas
quarkus.hibernate-orm.log.sql=true